// <auto-generated />
using System;
using CRM.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRM.DataAccess.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    partial class CrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CRM.Domain.Entities.Client", b =>
                {
                    b.Property<string>("NoClient")
                        .HasMaxLength(7)
                        .HasColumnType("char(7)")
                        .IsFixedLength();

                    b.Property<string>("Adresse")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("CodePostal")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Courriel")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("EstActif")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ville")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("NoClient");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.Contrat", b =>
                {
                    b.Property<int>("NoContrat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NoContrat"));

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MontantMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NoClient")
                        .IsRequired()
                        .HasColumnType("char(7)");

                    b.HasKey("NoContrat");

                    b.HasIndex("NoClient");

                    b.ToTable("Contrats", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.ItemContrat", b =>
                {
                    b.Property<int>("NoItemContrat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NoItemContrat"));

                    b.Property<string>("DescriptionProduit")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("NoContrat")
                        .HasColumnType("int");

                    b.Property<string>("NoProduit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("QuotaMax")
                        .HasColumnType("int");

                    b.Property<int>("QuotaMin")
                        .HasColumnType("int");

                    b.HasKey("NoItemContrat");

                    b.HasIndex("NoContrat", "NoProduit")
                        .IsUnique();

                    b.ToTable("ItemsContrat", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("NoTransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NoTransaction"));

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("DateTransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NoContrat")
                        .HasColumnType("int");

                    b.Property<string>("NoProduit")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("NoUtilisateur")
                        .HasColumnType("int");

                    b.Property<int?>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TypeTransaction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("NoTransaction");

                    b.HasIndex("NoContrat");

                    b.HasIndex("NoUtilisateur");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<int>("NoUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NoUtilisateur"));

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("DateModification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("EstActif")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("NoUtilisateur");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Utilisateurs", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.Contrat", b =>
                {
                    b.HasOne("CRM.Domain.Entities.Client", "Client")
                        .WithMany("Contrats")
                        .HasForeignKey("NoClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CRM.Domain.Entities.ItemContrat", b =>
                {
                    b.HasOne("CRM.Domain.Entities.Contrat", "Contrat")
                        .WithMany("Items")
                        .HasForeignKey("NoContrat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrat");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("CRM.Domain.Entities.Contrat", "Contrat")
                        .WithMany("Transactions")
                        .HasForeignKey("NoContrat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("NoUtilisateur")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contrat");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Client", b =>
                {
                    b.Navigation("Contrats");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Contrat", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
